"""Minimal bug reproduction script generator for reported open source issues."""

import re
from typing import Optional, Tuple


class ReproGenerator:
    """Constructs minimal, standalone, runnable reproduction scripts from issue descriptions."""

    @classmethod
    def generate(
        cls,
        repo_owner: str,
        repo_name: str,
        title: str,
        body: Optional[str],
        primary_lang: str = "Python",
    ) -> Tuple[str, str, str]:
        """
        Extracts code snippet from markdown or scaffolds a standalone test script.
        Returns: (reproduction_code, reproduction_lang, reproduction_instructions).
        """
        body_text = body or ""
        lang_lower = primary_lang.lower()

        # Try to find code blocks in issue description
        code_blocks = re.findall(r"```([a-zA-Z0-9_\+\-]+)?\n(.*?)```", body_text, re.DOTALL)

        extracted_snippet: Optional[str] = None
        target_lang = "python"

        for lang_tag, code_content in code_blocks:
            cleaned = code_content.strip()
            # Ignore stack traces / logs
            if "Traceback (most recent call last):" in cleaned or "Error:" in cleaned:
                continue
            if len(cleaned) > 20:
                extracted_snippet = cleaned
                if lang_tag:
                    target_lang = lang_tag.lower()
                break

        if extracted_snippet:
            repro_code = cls._wrap_snippet(extracted_snippet, repo_owner, repo_name, target_lang)
        else:
            repro_code = cls._scaffold_default_repro(repo_owner, repo_name, title, target_lang)

        instructions = (
            f"1. Save the snippet to `reproduce_{repo_name.lower()}_issue.py`.\n"
            f"2. Ensure `{repo_name.lower()}` is installed in your local environment.\n"
            f"3. Run `python reproduce_{repo_name.lower()}_issue.py` to observe the failure.\n"
            f"4. Once the fix is applied, the script should exit with status 0."
        )

        return repro_code, target_lang, instructions

    @classmethod
    def _wrap_snippet(cls, snippet: str, owner: str, repo: str, lang: str) -> str:
        """Wrap extracted snippet with assertions and try/except harness."""
        if lang in ("python", "py"):
            return (
                f"# Standalone Bug Reproduction for {owner}/{repo}\n"
                f"# Generated by GitScout AI Triage Engine\n\n"
                f"import sys\n\n"
                f"def run_repro():\n"
                f"    print('[*] Starting minimal reproduction scenario...')\n"
                f"    try:\n"
                f"        # Extracted user scenario:\n"
                f"{cls._indent(snippet, 8)}\n\n"
                f"        print('[!] If this line is reached without error, bug may be fixed or unresolved.')\n"
                f"    except Exception as err:\n"
                f"        print(f'[+] Reproduction successful: caught expected exception -> {{type(err).__name__}}: {{err}}')\n"
                f"        sys.exit(1)\n\n"
                f"if __name__ == '__main__':\n"
                f"    run_repro()\n"
            )
        else:
            return (
                f"// Bug Reproduction for {owner}/{repo}\n"
                f"// Generated by GitScout AI Triage Engine\n\n"
                f"{snippet}\n"
            )

    @classmethod
    def _scaffold_default_repro(cls, owner: str, repo: str, title: str, lang: str) -> str:
        """Scaffold a baseline executable test case when no explicit code block is in the description."""
        mod_name = repo.lower().replace("-", "_")
        return (
            f"# Standalone Test Case for {owner}/{repo}\n"
            f"# Issue: {title}\n\n"
            f"import pytest\n"
            f"try:\n"
            f"    import {mod_name}\n"
            f"except ImportError:\n"
            f"    {mod_name} = None\n\n"
            f"def test_issue_behavior():\n"
            f"    assert {mod_name} is not None, '{mod_name} must be installed in environment'\n"
            f"    print(f'Testing behavior against module: {mod_name}')\n"
        )

    @classmethod
    def _indent(cls, text: str, spaces: int) -> str:
        pad = " " * spaces
        return "\n".join(pad + line if line.strip() else line for line in text.splitlines())
