import { Domain, Difficulty, Issue } from '@/types/issue';
import { PricingPlan } from '@/types/billing';
import { ASTGraphData } from '@/types/graph';

export const SITE_CONFIG = {
  name: 'GitScout',
  terminalName: 'OSS Terminal v1.0.0',
  tagline: 'High-Throughput Open-Source Intelligence & Contribution Terminal',
  description:
    'Index, triage, and AI-localize live GitHub issues and bounties across AI/ML, Data, and Web ecosystems. Step-by-step fix blueprints, AST file mapping, and sub-second multi-channel alerts.',
  url: 'https://gitscout.dev',
  author: 'GitScout Core Engineering',
  links: {
    github: 'https://github.com/gitscout/oss-terminal',
    twitter: 'https://twitter.com/gitscout_app',
    discord: 'https://discord.gg/gitscout',
    telegram: 'https://t.me/GitScoutAlertsBot',
  },
};

export const DOMAINS: { id: Domain; label: string; description: string; icon: string }[] = [
  { id: 'ai_ml', label: 'AI & ML', description: 'PyTorch, vLLM, LangChain, Transformers, Ollama', icon: 'Sparkles' },
  { id: 'data', label: 'Data & Infra', description: 'DuckDB, ClickHouse, Polars, Apache Arrow, Spark', icon: 'Database' },
  { id: 'web', label: 'Web Ecosystem', description: 'Next.js, Tailwind, Fastify, Astro, Svelte', icon: 'Globe' },
  { id: 'cloud_devops', label: 'Cloud & DevOps', description: 'Kubernetes, Terraform, Docker, Envoy, Helm', icon: 'Cloud' },
  { id: 'security', label: 'Security', description: 'Trivy, Falco, Semgrep, OWASP ZAP, Cosign', icon: 'ShieldAlert' },
  { id: 'systems', label: 'Systems & OS', description: 'Linux, Rust Lang, Bun, Tokio, Zig', icon: 'Cpu' },
];

export const TECH_STACKS = [
  'Python',
  'TypeScript',
  'Rust',
  'Go',
  'C++',
  'JavaScript',
  'C',
  'Docker',
  'PyTorch',
  'CUDA',
  'React',
  'SQL',
];

export const DIFFICULTIES: { id: Difficulty; label: string }[] = [
  { id: 'easy', label: 'Good First Issue (<1h)' },
  { id: 'medium', label: 'Intermediate (1-3h)' },
  { id: 'hard', label: 'Advanced (4h+)' },
];

export const TIME_TO_SOLVE_OPTIONS = [
  { id: 'all', label: 'All Durations' },
  { id: 'lt_30m', label: '< 30 mins' },
  { id: '30m_2h', label: '30 mins – 2 hours' },
  { id: '2h_6h', label: '2 hours – 6 hours' },
  { id: 'gt_6h', label: '6+ hours' },
];

export const SORT_OPTIONS = [
  { id: 'created_desc', label: 'Newest Issues' },
  { id: 'roi_desc', label: 'Highest Hourly ROI ($/hr)' },
  { id: 'bounty_desc', label: 'Largest Bounty ($ USD)' },
  { id: 'time_asc', label: 'Fastest to Solve' },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'free',
    name: 'Community Hacker',
    tagline: 'Essential intelligence for casual open-source contributors',
    priceMonthlyUsd: 0,
    priceAnnualUsd: 0,
    features: [
      { title: 'Live GitHub Issue Terminal', included: true },
      { title: 'Faceted Search & Tech Stack Filtering', included: true },
      { title: 'Standard Problem Breakdown & Diagnostics', included: true },
      { title: 'Bounty Aggregation (Polar, Algora)', included: true },
      { title: 'Community Discord Channel Alerts', included: true },
      { title: 'Real-time Sub-60s Push Alerts', included: false },
      { title: 'Full AST Dependency Blast Radius Graph', included: false },
      { title: 'Automated Minimal Repro Script Generator', included: false },
      { title: 'CONTRIBUTING.md Step-by-Step Fix Blueprint', included: false },
      { title: 'Private Telegram Bot & Discord Webhooks', included: false },
    ],
    ctaText: 'Current Plan',
  },
  {
    id: 'pro',
    name: 'Pro Contributor',
    tagline: 'For aggressive bounty hunters and high-velocity OSS maintainers',
    priceMonthlyUsd: 19,
    priceAnnualUsd: 15, // $180 billed annually (20% off)
    popular: true,
    features: [
      { title: 'Everything in Community Hacker', included: true },
      { title: 'Real-Time Sub-60s Zero-Latency Alerts', included: true, highlight: true },
      { title: 'Private Telegram Bot & Discord Webhook Pairing', included: true, highlight: true },
      { title: 'Full AST Dependency & Blast Radius Visualizer', included: true, highlight: true },
      { title: 'AI-Generated Minimal Repro Test Sandboxes', included: true },
      { title: 'CONTRIBUTING.md-Compliant 4-Step PR Fix Blueprints', included: true },
      { title: 'Effective Hourly ROI & Effort-to-Bounty Scoring', included: true },
      { title: 'Unlimited Daily Issue & Bounty Inspections', included: true },
      { title: 'Export Verified Proof-of-Work Badges for GitHub', included: true },
      { title: 'Team Seat Sharing & Issue Claim Locking', included: false },
    ],
    ctaText: 'Upgrade to Pro',
  },
  {
    id: 'team',
    name: 'Engineering Team',
    tagline: 'For engineering organizations, devrel teams, and open-source startups',
    priceMonthlyUsd: 49,
    priceAnnualUsd: 39, // $468 billed annually
    features: [
      { title: 'Everything in Pro Contributor', included: true },
      { title: '5 Dedicated Developer Seats', included: true, highlight: true },
      { title: 'Shared Issue Claim Locking & Workspace Sync', included: true },
      { title: 'Custom Target Repository Crawls on Demand', included: true, highlight: true },
      { title: 'Webhook API Export & Slack Integration', included: true },
      { title: 'Dedicated Priority Email & Discord VIP Channel', included: true },
      { title: 'Custom AST Static Analysis Engine Integration', included: true },
    ],
    ctaText: 'Deploy Team Terminal',
  },
];

export const SAMPLE_GRAPH_DATA: ASTGraphData = {
  metadata: {
    totalFiles: 42,
    totalFunctions: 138,
    totalClasses: 27,
    generatedAt: new Date().toISOString(),
    repoName: 'vllm-project/vllm',
  },
  godNodes: ['vllm/model_executor/layers/quant.py', 'csrc/quantization/fp8_gemm.cu', 'vllm/engine/llm_engine.py'],
  communities: {
    1: {
      id: 1,
      name: 'CUDA Quantization Kernels',
      color: '#a855f7',
      nodeCount: 14,
      description: 'FP8 and INT4 low-level CUDA matrix multiply routines and memory managers',
    },
    2: {
      id: 2,
      name: 'Model Executor Layers',
      color: '#06b6d4',
      nodeCount: 18,
      description: 'PyTorch model layer implementations, attention mechanisms, and weights loader',
    },
    3: {
      id: 3,
      name: 'Async Engine & Scheduler',
      color: '#10b981',
      nodeCount: 10,
      description: 'Continuous batching scheduler, request queues, and token cache memory manager',
    },
  },
  nodes: [
    {
      id: 'csrc/quantization/fp8_gemm.cu',
      label: 'fp8_gemm.cu',
      type: 'file',
      communityId: 1,
      communityName: 'CUDA Quantization Kernels',
      confidence: 0.96,
      degree: 8,
      isGodNode: true,
      isTarget: true,
      blastRadiusConfidence: 0.94,
    },
    {
      id: 'csrc/quantization/fp8_gemm.cu::fp8_gemm_kernel',
      label: 'fp8_gemm_kernel()',
      type: 'function',
      file: 'csrc/quantization/fp8_gemm.cu',
      line: 142,
      communityId: 1,
      communityName: 'CUDA Quantization Kernels',
      confidence: 0.98,
      degree: 4,
      isTarget: true,
    },
    {
      id: 'vllm/model_executor/layers/quant.py',
      label: 'quant.py',
      type: 'file',
      communityId: 2,
      communityName: 'Model Executor Layers',
      confidence: 0.88,
      degree: 9,
      isGodNode: true,
      isTarget: true,
      blastRadiusConfidence: 0.85,
    },
    {
      id: 'vllm/model_executor/layers/quant.py::FP8LinearMethod',
      label: 'FP8LinearMethod',
      type: 'class',
      file: 'vllm/model_executor/layers/quant.py',
      line: 54,
      communityId: 2,
      communityName: 'Model Executor Layers',
      confidence: 0.91,
      degree: 5,
      isTarget: true,
    },
    {
      id: 'vllm/model_executor/models/llama.py',
      label: 'llama.py',
      type: 'file',
      communityId: 2,
      communityName: 'Model Executor Layers',
      confidence: 0.72,
      degree: 6,
    },
    {
      id: 'vllm/engine/llm_engine.py',
      label: 'llm_engine.py',
      type: 'file',
      communityId: 3,
      communityName: 'Async Engine & Scheduler',
      confidence: 0.65,
      degree: 12,
      isGodNode: true,
    },
    {
      id: 'vllm/core/scheduler.py',
      label: 'scheduler.py',
      type: 'file',
      communityId: 3,
      communityName: 'Async Engine & Scheduler',
      confidence: 0.58,
      degree: 7,
    },
    {
      id: 'tests/kernels/test_fp8.py',
      label: 'test_fp8.py',
      type: 'file',
      communityId: 1,
      communityName: 'CUDA Quantization Kernels',
      confidence: 0.89,
      degree: 3,
      isTarget: true,
    },
  ],
  edges: [
    {
      id: 'e1',
      source: 'vllm/model_executor/layers/quant.py::FP8LinearMethod',
      target: 'csrc/quantization/fp8_gemm.cu::fp8_gemm_kernel',
      relation: 'calls',
      confidence: 0.95,
      isExtracted: true,
    },
    {
      id: 'e2',
      source: 'vllm/model_executor/layers/quant.py',
      target: 'csrc/quantization/fp8_gemm.cu',
      relation: 'imports',
      confidence: 0.92,
      isExtracted: true,
    },
    {
      id: 'e3',
      source: 'vllm/model_executor/models/llama.py',
      target: 'vllm/model_executor/layers/quant.py::FP8LinearMethod',
      relation: 'instantiates',
      confidence: 0.88,
      isExtracted: true,
    },
    {
      id: 'e4',
      source: 'vllm/engine/llm_engine.py',
      target: 'vllm/core/scheduler.py',
      relation: 'calls',
      confidence: 0.9,
      isExtracted: true,
    },
    {
      id: 'e5',
      source: 'tests/kernels/test_fp8.py',
      target: 'csrc/quantization/fp8_gemm.cu::fp8_gemm_kernel',
      relation: 'calls',
      confidence: 0.94,
      isExtracted: true,
    },
    {
      id: 'e6',
      source: 'vllm/engine/llm_engine.py',
      target: 'vllm/model_executor/models/llama.py',
      relation: 'inferred',
      confidence: 0.76,
      isExtracted: false,
    },
  ],
};

export const SAMPLE_FALLBACK_ISSUES: Issue[] = [
  {
    id: 'vllm-project/vllm#4928',
    githubIssueNumber: 4928,
    title: 'Fix Quantization Kernel Overflow on FP8 Matrix Multiply with Large Batch Sizes',
    body: 'When running inference on Llama 3 70B with FP8 quantization enabled and batch sizes greater than 64, CUDA kernel execution fails with illegal memory access in fp8_gemm_kernel. The issue stems from integer overflow in stride offset calculations when matrix dimension M exceeds 2^16.',
    issueUrl: 'https://github.com/vllm-project/vllm/issues/4928',
    repository: {
      name: 'vllm',
      owner: 'vllm-project',
      stars: 28400,
      forks: 4100,
      language: 'Python',
      avatarUrl: 'https://avatars.githubusercontent.com/u/138139589?v=4',
      repoUrl: 'https://github.com/vllm-project/vllm',
      description: 'A high-throughput and memory-efficient LLM inference and serving engine',
    },
    domain: 'ai_ml',
    difficulty: 'medium',
    estimatedMinutesToSolve: 90,
    effortHours: 1.5,
    techStack: ['Python', 'C++', 'CUDA', 'PyTorch'],
    bounty: {
      amountUsd: 250,
      currency: 'USD',
      source: 'polar',
      sourceUrl: 'https://polar.sh/vllm-project/vllm/issues/4928',
      isFunded: true,
      claimed: false,
    },
    hourlyRoiUsd: 166.67,
    confidenceScore: 0.96,
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    hasTriageReport: true,
    labels: ['bug', 'kernel', 'bounty', 'quantization'],
    author: 'cuda_dev_99',
  },
  {
    id: 'duckdb/duckdb#11842',
    githubIssueNumber: 11842,
    title: 'Panic when streaming Parquet timestamp_tz with non-standard microsecond offsets',
    body: 'DuckDB raises an unexpected internal assertion failure when executing COPY or reading Parquet files containing timestamp_tz values originating from Snowflake with fractional offsets.',
    issueUrl: 'https://github.com/duckdb/duckdb/issues/11842',
    repository: {
      name: 'duckdb',
      owner: 'duckdb',
      stars: 21900,
      forks: 2300,
      language: 'C++',
      avatarUrl: 'https://avatars.githubusercontent.com/u/52090259?v=4',
      repoUrl: 'https://github.com/duckdb/duckdb',
      description: 'An in-process SQL OLAP database management system',
    },
    domain: 'data',
    difficulty: 'medium',
    estimatedMinutesToSolve: 120,
    effortHours: 2.0,
    techStack: ['C++', 'SQL', 'Parquet'],
    bounty: {
      amountUsd: 300,
      currency: 'USD',
      source: 'algora',
      sourceUrl: 'https://algora.io/bounties/duckdb/11842',
      isFunded: true,
      claimed: false,
    },
    hourlyRoiUsd: 150.0,
    confidenceScore: 0.93,
    createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    hasTriageReport: true,
    labels: ['bug', 'parquet', 'bounty:300'],
    author: 'data_pipeline_pro',
  },
  {
    id: 'fastify/fastify#5491',
    githubIssueNumber: 5491,
    title: 'Add TypeScript typings for custom HTTP/2 server push stream options',
    body: 'TypeScript definitions currently omit the options parameter on reply.raw.createPushStream in HTTP/2 mode, causing compiler errors in strict mode when specifying headers.',
    issueUrl: 'https://github.com/fastify/fastify/issues/5491',
    repository: {
      name: 'fastify',
      owner: 'fastify',
      stars: 31200,
      forks: 2400,
      language: 'TypeScript',
      avatarUrl: 'https://avatars.githubusercontent.com/u/24939410?v=4',
      repoUrl: 'https://github.com/fastify/fastify',
      description: 'Fast and low overhead web framework, for Node.js',
    },
    domain: 'web',
    difficulty: 'easy',
    estimatedMinutesToSolve: 45,
    effortHours: 0.75,
    techStack: ['TypeScript', 'Node.js', 'HTTP/2'],
    bounty: {
      amountUsd: 100,
      currency: 'USD',
      source: 'github_sponsors',
      sourceUrl: 'https://github.com/sponsors/fastify',
      isFunded: true,
      claimed: false,
    },
    hourlyRoiUsd: 133.33,
    confidenceScore: 0.98,
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    hasTriageReport: true,
    labels: ['good first issue', 'typescript', 'types'],
    author: 'type_ninja',
  },
  {
    id: 'aquasecurity/trivy#6820',
    githubIssueNumber: 6820,
    title: 'False negative in CycloneDX SBOM export for transitive Go module vulnerabilities',
    body: 'When scanning a multi-module Go workspace, Trivy skips reporting CVEs in second-order indirect dependencies if the indirect tag is nested in a vendor sub-directory.',
    issueUrl: 'https://github.com/aquasecurity/trivy/issues/6820',
    repository: {
      name: 'trivy',
      owner: 'aquasecurity',
      stars: 23600,
      forks: 2100,
      language: 'Go',
      avatarUrl: 'https://avatars.githubusercontent.com/u/17855077?v=4',
      repoUrl: 'https://github.com/aquasecurity/trivy',
      description: 'Find vulnerabilities, misconfigurations, secrets, SBOM in containers, Kubernetes, code',
    },
    domain: 'security',
    difficulty: 'medium',
    estimatedMinutesToSolve: 150,
    effortHours: 2.5,
    techStack: ['Go', 'Docker', 'SBOM', 'CycloneDX'],
    bounty: {
      amountUsd: 350,
      currency: 'USD',
      source: 'polar',
      sourceUrl: 'https://polar.sh/aquasecurity/trivy/issues/6820',
      isFunded: true,
      claimed: false,
    },
    hourlyRoiUsd: 140.0,
    confidenceScore: 0.91,
    createdAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 10).toISOString(),
    hasTriageReport: true,
    labels: ['scanner/golang', 'sbom', 'bounty'],
    author: 'sec_auditor',
  },
  {
    id: 'tokio-rs/tokio#6712',
    githubIssueNumber: 6712,
    title: 'Avoid unnecessary atomic fetch_add in LocalSet unparking on single-threaded runtime',
    body: 'Profiling shows ~3.2% CPU overhead in single-core task queue management caused by unconditional atomic synchronization when LocalSet has no multi-threaded workers.',
    issueUrl: 'https://github.com/tokio-rs/tokio/issues/6712',
    repository: {
      name: 'tokio',
      owner: 'tokio-rs',
      stars: 26800,
      forks: 2600,
      language: 'Rust',
      avatarUrl: 'https://avatars.githubusercontent.com/u/17571932?v=4',
      repoUrl: 'https://github.com/tokio-rs/tokio',
      description: 'A runtime for writing reliable, asynchronous, and slim applications with the Rust programming language.',
    },
    domain: 'systems',
    difficulty: 'hard',
    estimatedMinutesToSolve: 240,
    effortHours: 4.0,
    techStack: ['Rust', 'Async', 'Atomics', 'Concurrency'],
    bounty: {
      amountUsd: 500,
      currency: 'USD',
      source: 'algora',
      sourceUrl: 'https://algora.io/bounties/tokio/6712',
      isFunded: true,
      claimed: false,
    },
    hourlyRoiUsd: 125.0,
    confidenceScore: 0.95,
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 14).toISOString(),
    hasTriageReport: true,
    labels: ['performance', 'runtime', 'rust', 'bounty:500'],
    author: 'rust_hacker_42',
  },
  {
    id: 'kubernetes/kubernetes#125430',
    githubIssueNumber: 125430,
    title: 'Kubelet fails to release orphaned cgroup directories on systemd reload under cgroups v2',
    body: 'Under systemd cgroup v2, when node restart or systemctl daemon-reload is executed while pods are terminating, the kubelet fails to prune leaf controller paths resulting in cgroup memory leakage.',
    issueUrl: 'https://github.com/kubernetes/kubernetes/issues/125430',
    repository: {
      name: 'kubernetes',
      owner: 'kubernetes',
      stars: 111000,
      forks: 39000,
      language: 'Go',
      avatarUrl: 'https://avatars.githubusercontent.com/u/13629408?v=4',
      repoUrl: 'https://github.com/kubernetes/kubernetes',
      description: 'Production-Grade Container Scheduling and Management',
    },
    domain: 'cloud_devops',
    difficulty: 'hard',
    estimatedMinutesToSolve: 300,
    effortHours: 5.0,
    techStack: ['Go', 'Kubernetes', 'Linux', 'cgroups'],
    bounty: {
      amountUsd: 600,
      currency: 'USD',
      source: 'polar',
      sourceUrl: 'https://polar.sh/kubernetes/kubernetes/issues/125430',
      isFunded: true,
      claimed: false,
    },
    hourlyRoiUsd: 120.0,
    confidenceScore: 0.92,
    createdAt: new Date(Date.now() - 3600000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 16).toISOString(),
    hasTriageReport: true,
    labels: ['sig/node', 'area/kubelet', 'cgroups-v2'],
    author: 'k8s_node_lead',
  },
];
