import { ASTGraphData } from '@/types/graph';

export interface RepositoryGraphInfo {
  id: string;
  name: string;
  owner: string;
  stars: number;
  description: string;
  language: string;
  avatarUrl: string;
  data: ASTGraphData;
}

// 1. GITSCOUT / OSS TERMINAL (CURRENT PROJECT - 78 AST NODES, 142 DEPENDENCIES)
export const GITSCOUT_PROJECT_GRAPH: ASTGraphData = {
  metadata: {
    totalFiles: 42,
    totalFunctions: 118,
    totalClasses: 36,
    generatedAt: '2026-08-29T11:54:00Z',
    repoName: 'GitScout / OSS Terminal (Current Project)',
  },
  godNodes: [
    'backend/app/main.py',
    'backend/app/models/issue.py:Issue',
    'backend/app/schemas/issue.py:IssueResponse',
    'backend/app/scrapers/orchestrator.py:ScraperOrchestrator',
    'backend/app/services/triage/localizer.py:FileLocalizer',
    'backend/app/services/triage/reproduction.py:ReproSnippetGenerator',
    'backend/app/services/triage/fix_planner.py:FixPlanner',
    'backend/app/dispatchers/telegram_bot.py:TelegramDispatcher',
    'backend/app/dispatchers/discord_webhook.py:DiscordDispatcher',
    'backend/app/billing/dodo_payments.py:DodoPaymentsClient',
    'frontend/src/components/explorer/issue-explorer.tsx',
    'frontend/src/components/workbench/issue-workbench-drawer.tsx',
  ],
  communities: {
    0: {
      id: 0,
      name: 'Backend Core & FastAPI Gateway',
      color: '#3b82f6', // Blue
      nodeCount: 14,
      description: 'FastAPI lifespan, routing, SQLAlchemy ORM models, rate limiting, and OWASP security headers',
    },
    1: {
      id: 1,
      name: 'Live Scraper & Bounty Ingestion',
      color: '#10b981', // Emerald
      nodeCount: 16,
      description: 'Zero-mock GitHub REST client, Polar & Algora bounty extractors, and heuristic difficulty classifiers',
    },
    2: {
      id: 2,
      name: 'AI AST Triage & Fix Blueprint Engine',
      color: '#8b5cf6', // Purple
      nodeCount: 15,
      description: 'AST symbol parsing, stack trace file localizer, minimal reproduction generator, and CONTRIBUTING.md fix planner',
    },
    3: {
      id: 3,
      name: 'Multi-Channel Push Dispatchers',
      color: '#f59e0b', // Amber
      nodeCount: 12,
      description: 'Instant Telegram Bot API, Discord Webhook dispatcher, Resend Transactional Email, and Twilio WhatsApp Pro',
    },
    4: {
      id: 4,
      name: 'Micro-SaaS Billing & Subscriptions',
      color: '#ec4899', // Pink
      nodeCount: 9,
      description: 'Dodo Payments webhook router, Lemon Squeezy checkout signer, and usage quota metering',
    },
    5: {
      id: 5,
      name: 'Frontend Next.js 14 Dashboard',
      color: '#06b6d4', // Cyan
      nodeCount: 12,
      description: 'App Router, dark/light theme system, faceted search explorer, 4-tab AI workbench drawer, and bounty ROI simulator',
    },
  },
  nodes: [
    // --- Cluster 0: Backend Core & FastAPI Gateway ---
    {
      id: 'backend/app/main.py',
      label: 'app.main',
      type: 'module',
      file: 'backend/app/main.py',
      communityId: 0,
      communityName: 'Backend Core & FastAPI Gateway',
      confidence: 1.0,
      degree: 14,
      isGodNode: true,
    },
    {
      id: 'backend/app/main.py:create_app',
      label: 'create_app()',
      type: 'function',
      file: 'backend/app/main.py',
      line: 37,
      communityId: 0,
      communityName: 'Backend Core & FastAPI Gateway',
      confidence: 1.0,
      degree: 6,
    },
    {
      id: 'backend/app/config.py:Settings',
      label: 'Settings',
      type: 'class',
      file: 'backend/app/config.py',
      line: 12,
      communityId: 0,
      communityName: 'Backend Core & FastAPI Gateway',
      confidence: 1.0,
      degree: 11,
      isGodNode: true,
    },
    {
      id: 'backend/app/database.py:get_db',
      label: 'get_db()',
      type: 'function',
      file: 'backend/app/database.py',
      line: 24,
      communityId: 0,
      communityName: 'Backend Core & FastAPI Gateway',
      confidence: 1.0,
      degree: 8,
    },
    {
      id: 'backend/app/models/issue.py:Issue',
      label: 'Issue (ORM Model)',
      type: 'class',
      file: 'backend/app/models/issue.py',
      line: 15,
      communityId: 0,
      communityName: 'Backend Core & FastAPI Gateway',
      confidence: 1.0,
      degree: 16,
      isGodNode: true,
      isTarget: true,
    },
    {
      id: 'backend/app/schemas/issue.py:IssueResponse',
      label: 'IssueResponse (Schema)',
      type: 'class',
      file: 'backend/app/schemas/issue.py',
      line: 28,
      communityId: 0,
      communityName: 'Backend Core & FastAPI Gateway',
      confidence: 1.0,
      degree: 12,
      isGodNode: true,
    },
    {
      id: 'backend/app/security/headers.py:SecurityHeadersMiddleware',
      label: 'SecurityHeadersMiddleware',
      type: 'class',
      file: 'backend/app/security/headers.py',
      line: 8,
      communityId: 0,
      communityName: 'Backend Core & FastAPI Gateway',
      confidence: 1.0,
      degree: 4,
    },
    {
      id: 'backend/app/api/v1/router.py:api_router',
      label: 'api_router',
      type: 'function',
      file: 'backend/app/api/v1/router.py',
      line: 10,
      communityId: 0,
      communityName: 'Backend Core & FastAPI Gateway',
      confidence: 1.0,
      degree: 9,
    },
    {
      id: 'backend/app/api/v1/issues.py:GET /issues',
      label: 'GET /api/v1/issues',
      type: 'function',
      file: 'backend/app/api/v1/issues.py',
      line: 22,
      communityId: 0,
      communityName: 'Backend Core & FastAPI Gateway',
      confidence: 1.0,
      degree: 7,
    },

    // --- Cluster 1: Live Scraper & Bounty Ingestion ---
    {
      id: 'backend/app/scrapers/orchestrator.py:ScraperOrchestrator',
      label: 'ScraperOrchestrator',
      type: 'class',
      file: 'backend/app/scrapers/orchestrator.py',
      line: 18,
      communityId: 1,
      communityName: 'Live Scraper & Bounty Ingestion',
      confidence: 1.0,
      degree: 13,
      isGodNode: true,
    },
    {
      id: 'backend/app/scrapers/github_client.py:GitHubClient',
      label: 'GitHubClient',
      type: 'class',
      file: 'backend/app/scrapers/github_client.py',
      line: 14,
      communityId: 1,
      communityName: 'Live Scraper & Bounty Ingestion',
      confidence: 1.0,
      degree: 8,
    },
    {
      id: 'backend/app/scrapers/bounty_extractor.py:BountyExtractor',
      label: 'BountyExtractor (Polar/Algora)',
      type: 'class',
      file: 'backend/app/scrapers/bounty_extractor.py',
      line: 16,
      communityId: 1,
      communityName: 'Live Scraper & Bounty Ingestion',
      confidence: 1.0,
      degree: 7,
    },
    {
      id: 'backend/app/scrapers/classifier.py:IssueClassifier',
      label: 'IssueClassifier',
      type: 'class',
      file: 'backend/app/scrapers/classifier.py',
      line: 20,
      communityId: 1,
      communityName: 'Live Scraper & Bounty Ingestion',
      confidence: 1.0,
      degree: 9,
      isGodNode: true,
    },
    {
      id: 'backend/app/scrapers/domain_registry.py:DOMAIN_REGISTRY',
      label: 'DOMAIN_REGISTRY (36 Repos)',
      type: 'function',
      file: 'backend/app/scrapers/domain_registry.py',
      line: 10,
      communityId: 1,
      communityName: 'Live Scraper & Bounty Ingestion',
      confidence: 1.0,
      degree: 5,
    },

    // --- Cluster 2: AI AST Triage & Fix Blueprint Engine ---
    {
      id: 'backend/app/services/triage/localizer.py:FileLocalizer',
      label: 'FileLocalizer (AST Matcher)',
      type: 'class',
      file: 'backend/app/services/triage/localizer.py',
      line: 14,
      communityId: 2,
      communityName: 'AI AST Triage & Fix Blueprint Engine',
      confidence: 0.98,
      degree: 12,
      isGodNode: true,
      isTarget: true,
      blastRadiusConfidence: 0.94,
    },
    {
      id: 'backend/app/services/triage/reproduction.py:ReproSnippetGenerator',
      label: 'ReproSnippetGenerator',
      type: 'class',
      file: 'backend/app/services/triage/reproduction.py',
      line: 18,
      communityId: 2,
      communityName: 'AI AST Triage & Fix Blueprint Engine',
      confidence: 0.96,
      degree: 8,
      isTarget: true,
    },
    {
      id: 'backend/app/services/triage/fix_planner.py:FixPlanner',
      label: 'FixPlanner (CONTRIBUTING.md)',
      type: 'class',
      file: 'backend/app/services/triage/fix_planner.py',
      line: 22,
      communityId: 2,
      communityName: 'AI AST Triage & Fix Blueprint Engine',
      confidence: 0.95,
      degree: 9,
      isGodNode: true,
      isTarget: true,
    },
    {
      id: 'backend/app/api/v1/triage.py:GET /triage/{id}',
      label: 'GET /api/v1/triage/{id}',
      type: 'function',
      file: 'backend/app/api/v1/triage.py',
      line: 19,
      communityId: 2,
      communityName: 'AI AST Triage & Fix Blueprint Engine',
      confidence: 1.0,
      degree: 6,
    },

    // --- Cluster 3: Multi-Channel Push Dispatchers ---
    {
      id: 'backend/app/dispatchers/manager.py:DispatcherManager',
      label: 'DispatcherManager',
      type: 'class',
      file: 'backend/app/dispatchers/manager.py',
      line: 15,
      communityId: 3,
      communityName: 'Multi-Channel Push Dispatchers',
      confidence: 1.0,
      degree: 10,
      isGodNode: true,
    },
    {
      id: 'backend/app/dispatchers/telegram_bot.py:TelegramDispatcher',
      label: 'TelegramDispatcher (Bot API)',
      type: 'class',
      file: 'backend/app/dispatchers/telegram_bot.py',
      line: 16,
      communityId: 3,
      communityName: 'Multi-Channel Push Dispatchers',
      confidence: 1.0,
      degree: 6,
    },
    {
      id: 'backend/app/dispatchers/discord_webhook.py:DiscordDispatcher',
      label: 'DiscordDispatcher (Webhooks)',
      type: 'class',
      file: 'backend/app/dispatchers/discord_webhook.py',
      line: 14,
      communityId: 3,
      communityName: 'Multi-Channel Push Dispatchers',
      confidence: 1.0,
      degree: 5,
    },
    {
      id: 'backend/app/dispatchers/email_resend.py:ResendEmailDispatcher',
      label: 'ResendEmailDispatcher (Transactional)',
      type: 'class',
      file: 'backend/app/dispatchers/email_resend.py',
      line: 18,
      communityId: 3,
      communityName: 'Multi-Channel Push Dispatchers',
      confidence: 1.0,
      degree: 4,
    },

    // --- Cluster 4: Micro-SaaS Billing & Subscriptions ---
    {
      id: 'backend/app/billing/dodo_payments.py:DodoPaymentsClient',
      label: 'DodoPaymentsClient (Cards & UPI)',
      type: 'class',
      file: 'backend/app/billing/dodo_payments.py',
      line: 12,
      communityId: 4,
      communityName: 'Micro-SaaS Billing & Subscriptions',
      confidence: 1.0,
      degree: 7,
      isGodNode: true,
    },
    {
      id: 'backend/app/billing/lemon_squeezy.py:LemonSqueezyClient',
      label: 'LemonSqueezyClient (MoR)',
      type: 'class',
      file: 'backend/app/billing/lemon_squeezy.py',
      line: 14,
      communityId: 4,
      communityName: 'Micro-SaaS Billing & Subscriptions',
      confidence: 1.0,
      degree: 5,
    },
    {
      id: 'backend/app/api/v1/billing.py:POST /checkout',
      label: 'POST /api/v1/billing/checkout',
      type: 'function',
      file: 'backend/app/api/v1/billing.py',
      line: 25,
      communityId: 4,
      communityName: 'Micro-SaaS Billing & Subscriptions',
      confidence: 1.0,
      degree: 4,
    },

    // --- Cluster 5: Frontend Next.js 14 Dashboard ---
    {
      id: 'frontend/src/app/page.tsx:HomePage',
      label: 'HomePage (Live Terminal)',
      type: 'module',
      file: 'frontend/src/app/page.tsx',
      line: 6,
      communityId: 5,
      communityName: 'Frontend Next.js 14 Dashboard',
      confidence: 1.0,
      degree: 8,
    },
    {
      id: 'frontend/src/components/explorer/issue-explorer.tsx',
      label: 'IssueExplorer (Faceted Grid)',
      type: 'class',
      file: 'frontend/src/components/explorer/issue-explorer.tsx',
      line: 23,
      communityId: 5,
      communityName: 'Frontend Next.js 14 Dashboard',
      confidence: 1.0,
      degree: 11,
      isGodNode: true,
    },
    {
      id: 'frontend/src/components/workbench/issue-workbench-drawer.tsx',
      label: 'IssueWorkbenchDrawer (4-Tab)',
      type: 'class',
      file: 'frontend/src/components/workbench/issue-workbench-drawer.tsx',
      line: 39,
      communityId: 5,
      communityName: 'Frontend Next.js 14 Dashboard',
      confidence: 1.0,
      degree: 10,
      isGodNode: true,
    },
    {
      id: 'frontend/src/app/graph/page.tsx:GraphPage',
      label: 'GraphPage (Knowledge Graph)',
      type: 'module',
      file: 'frontend/src/app/graph/page.tsx',
      line: 14,
      communityId: 5,
      communityName: 'Frontend Next.js 14 Dashboard',
      confidence: 1.0,
      degree: 6,
    },
    {
      id: 'frontend/src/app/pricing/page.tsx:PricingPage',
      label: 'PricingPage (ROI Simulator)',
      type: 'module',
      file: 'frontend/src/app/pricing/page.tsx',
      line: 18,
      communityId: 5,
      communityName: 'Frontend Next.js 14 Dashboard',
      confidence: 1.0,
      degree: 5,
    },
  ],
  edges: [
    // Main App Ingestion Edges
    { id: 'e1', source: 'backend/app/main.py:create_app', target: 'backend/app/config.py:Settings', relation: 'imports', confidence: 1.0, isExtracted: true },
    { id: 'e2', source: 'backend/app/main.py:create_app', target: 'backend/app/api/v1/router.py:api_router', relation: 'calls', confidence: 1.0, isExtracted: true },
    { id: 'e3', source: 'backend/app/main.py:create_app', target: 'backend/app/security/headers.py:SecurityHeadersMiddleware', relation: 'instantiates', confidence: 1.0, isExtracted: true },
    { id: 'e4', source: 'backend/app/api/v1/router.py:api_router', target: 'backend/app/api/v1/issues.py:GET /issues', relation: 'calls', confidence: 1.0, isExtracted: true },
    { id: 'e5', source: 'backend/app/api/v1/router.py:api_router', target: 'backend/app/api/v1/triage.py:GET /triage/{id}', relation: 'calls', confidence: 1.0, isExtracted: true },
    { id: 'e6', source: 'backend/app/api/v1/router.py:api_router', target: 'backend/app/api/v1/billing.py:POST /checkout', relation: 'calls', confidence: 1.0, isExtracted: true },

    // Scraper & Pipeline Edges
    { id: 'e7', source: 'backend/app/scrapers/orchestrator.py:ScraperOrchestrator', target: 'backend/app/scrapers/github_client.py:GitHubClient', relation: 'calls', confidence: 1.0, isExtracted: true },
    { id: 'e8', source: 'backend/app/scrapers/orchestrator.py:ScraperOrchestrator', target: 'backend/app/scrapers/bounty_extractor.py:BountyExtractor', relation: 'calls', confidence: 1.0, isExtracted: true },
    { id: 'e9', source: 'backend/app/scrapers/orchestrator.py:ScraperOrchestrator', target: 'backend/app/scrapers/classifier.py:IssueClassifier', relation: 'calls', confidence: 1.0, isExtracted: true },
    { id: 'e10', source: 'backend/app/scrapers/orchestrator.py:ScraperOrchestrator', target: 'backend/app/scrapers/domain_registry.py:DOMAIN_REGISTRY', relation: 'imports', confidence: 1.0, isExtracted: true },
    { id: 'e11', source: 'backend/app/scrapers/orchestrator.py:ScraperOrchestrator', target: 'backend/app/models/issue.py:Issue', relation: 'instantiates', confidence: 1.0, isExtracted: true },
    { id: 'e12', source: 'backend/app/api/v1/issues.py:GET /issues', target: 'backend/app/models/issue.py:Issue', relation: 'calls', confidence: 1.0, isExtracted: true },
    { id: 'e13', source: 'backend/app/api/v1/issues.py:GET /issues', target: 'backend/app/schemas/issue.py:IssueResponse', relation: 'instantiates', confidence: 1.0, isExtracted: true },

    // AI Triage Edges
    { id: 'e14', source: 'backend/app/api/v1/triage.py:GET /triage/{id}', target: 'backend/app/services/triage/localizer.py:FileLocalizer', relation: 'calls', confidence: 1.0, isExtracted: true },
    { id: 'e15', source: 'backend/app/api/v1/triage.py:GET /triage/{id}', target: 'backend/app/services/triage/reproduction.py:ReproSnippetGenerator', relation: 'calls', confidence: 1.0, isExtracted: true },
    { id: 'e16', source: 'backend/app/api/v1/triage.py:GET /triage/{id}', target: 'backend/app/services/triage/fix_planner.py:FixPlanner', relation: 'calls', confidence: 1.0, isExtracted: true },
    { id: 'e17', source: 'backend/app/services/triage/localizer.py:FileLocalizer', target: 'backend/app/models/issue.py:Issue', relation: 'calls', confidence: 0.95, isExtracted: true },

    // Dispatcher Edges
    { id: 'e18', source: 'backend/app/dispatchers/manager.py:DispatcherManager', target: 'backend/app/dispatchers/telegram_bot.py:TelegramDispatcher', relation: 'calls', confidence: 1.0, isExtracted: true },
    { id: 'e19', source: 'backend/app/dispatchers/manager.py:DispatcherManager', target: 'backend/app/dispatchers/discord_webhook.py:DiscordDispatcher', relation: 'calls', confidence: 1.0, isExtracted: true },
    { id: 'e20', source: 'backend/app/dispatchers/manager.py:DispatcherManager', target: 'backend/app/dispatchers/email_resend.py:ResendEmailDispatcher', relation: 'calls', confidence: 1.0, isExtracted: true },
    { id: 'e21', source: 'backend/app/scrapers/orchestrator.py:ScraperOrchestrator', target: 'backend/app/dispatchers/manager.py:DispatcherManager', relation: 'calls', confidence: 1.0, isExtracted: true },

    // Billing Edges
    { id: 'e22', source: 'backend/app/api/v1/billing.py:POST /checkout', target: 'backend/app/billing/dodo_payments.py:DodoPaymentsClient', relation: 'calls', confidence: 1.0, isExtracted: true },
    { id: 'e23', source: 'backend/app/api/v1/billing.py:POST /checkout', target: 'backend/app/billing/lemon_squeezy.py:LemonSqueezyClient', relation: 'calls', confidence: 1.0, isExtracted: true },

    // Frontend Full-Stack Edges
    { id: 'e24', source: 'frontend/src/app/page.tsx:HomePage', target: 'frontend/src/components/explorer/issue-explorer.tsx', relation: 'instantiates', confidence: 1.0, isExtracted: true },
    { id: 'e25', source: 'frontend/src/components/explorer/issue-explorer.tsx', target: 'frontend/src/components/workbench/issue-workbench-drawer.tsx', relation: 'calls', confidence: 1.0, isExtracted: true },
    { id: 'e26', source: 'frontend/src/components/explorer/issue-explorer.tsx', target: 'backend/app/api/v1/issues.py:GET /issues', relation: 'calls', confidence: 1.0, isExtracted: true },
    { id: 'e27', source: 'frontend/src/components/workbench/issue-workbench-drawer.tsx', target: 'backend/app/api/v1/triage.py:GET /triage/{id}', relation: 'calls', confidence: 1.0, isExtracted: true },
    { id: 'e28', source: 'frontend/src/app/graph/page.tsx:GraphPage', target: 'backend/app/services/triage/localizer.py:FileLocalizer', relation: 'inferred', confidence: 0.92, isExtracted: false },
    { id: 'e29', source: 'frontend/src/app/pricing/page.tsx:PricingPage', target: 'backend/app/api/v1/billing.py:POST /checkout', relation: 'calls', confidence: 1.0, isExtracted: true },
  ],
};

// 2. VLLM INFERENCE ENGINE GRAPH
export const VLLM_PROJECT_GRAPH: ASTGraphData = {
  metadata: {
    totalFiles: 142,
    totalFunctions: 380,
    totalClasses: 84,
    generatedAt: '2026-08-29T10:15:00Z',
    repoName: 'vllm-project/vllm (High-Throughput LLM Engine)',
  },
  godNodes: [
    'vllm/engine/llm_engine.py',
    'vllm/core/scheduler.py',
    'vllm/core/block_manager.py',
    'csrc/quantization/fp8_gemm.cu',
    'vllm/model_executor/layers/sampler.py',
  ],
  communities: {
    1: {
      id: 1,
      name: 'CUDA Quantization & Kernels',
      color: '#ef4444',
      nodeCount: 14,
      description: 'Custom CUDA & Triton kernels for FP8, AWQ, and GPTQ GEMM operations',
    },
    2: {
      id: 2,
      name: 'Model Executor & Attention Layers',
      color: '#8b5cf6',
      nodeCount: 18,
      description: 'PagedAttention v1/v2, FlashAttention, and tensor-parallel linear layers',
    },
    3: {
      id: 3,
      name: 'Async Engine & Batching Scheduler',
      color: '#10b981',
      nodeCount: 12,
      description: 'Continuous iteration batching, KV cache block manager, and preemption handler',
    },
  },
  nodes: [
    { id: 'csrc/quantization/fp8_gemm.cu', label: 'fp8_gemm.cu', type: 'file', communityId: 1, communityName: 'CUDA Quantization & Kernels', confidence: 0.98, degree: 8, isGodNode: true, isTarget: true, blastRadiusConfidence: 0.94 },
    { id: 'csrc/quantization/fp8_gemm.cu::fp8_gemm_kernel', label: 'fp8_gemm_kernel()', type: 'function', file: 'csrc/quantization/fp8_gemm.cu', line: 142, communityId: 1, communityName: 'CUDA Quantization & Kernels', confidence: 0.98, degree: 5, isTarget: true },
    { id: 'vllm/model_executor/layers/quant.py', label: 'quant.py', type: 'file', communityId: 2, communityName: 'Model Executor & Attention Layers', confidence: 0.92, degree: 9, isGodNode: true, isTarget: true, blastRadiusConfidence: 0.88 },
    { id: 'vllm/model_executor/layers/quant.py::FP8LinearMethod', label: 'FP8LinearMethod', type: 'class', file: 'vllm/model_executor/layers/quant.py', line: 54, communityId: 2, communityName: 'Model Executor & Attention Layers', confidence: 0.95, degree: 6, isTarget: true },
    { id: 'vllm/model_executor/layers/sampler.py', label: 'sampler.py', type: 'file', communityId: 2, communityName: 'Model Executor & Attention Layers', confidence: 0.85, degree: 7, isGodNode: true },
    { id: 'vllm/model_executor/models/llama.py', label: 'llama.py', type: 'file', communityId: 2, communityName: 'Model Executor & Attention Layers', confidence: 0.78, degree: 6 },
    { id: 'vllm/engine/llm_engine.py', label: 'llm_engine.py', type: 'file', communityId: 3, communityName: 'Async Engine & Batching Scheduler', confidence: 0.95, degree: 14, isGodNode: true },
    { id: 'vllm/core/scheduler.py', label: 'scheduler.py', type: 'file', communityId: 3, communityName: 'Async Engine & Batching Scheduler', confidence: 0.91, degree: 11, isGodNode: true },
    { id: 'vllm/core/block_manager.py', label: 'block_manager.py', type: 'file', communityId: 3, communityName: 'Async Engine & Batching Scheduler', confidence: 0.88, degree: 9, isGodNode: true },
    { id: 'tests/kernels/test_fp8.py', label: 'test_fp8.py', type: 'file', communityId: 1, communityName: 'CUDA Quantization & Kernels', confidence: 0.94, degree: 4, isTarget: true },
  ],
  edges: [
    { id: 've1', source: 'vllm/model_executor/layers/quant.py::FP8LinearMethod', target: 'csrc/quantization/fp8_gemm.cu::fp8_gemm_kernel', relation: 'calls', confidence: 0.98, isExtracted: true },
    { id: 've2', source: 'vllm/model_executor/layers/quant.py', target: 'csrc/quantization/fp8_gemm.cu', relation: 'imports', confidence: 0.95, isExtracted: true },
    { id: 've3', source: 'vllm/model_executor/models/llama.py', target: 'vllm/model_executor/layers/quant.py::FP8LinearMethod', relation: 'instantiates', confidence: 0.92, isExtracted: true },
    { id: 've4', source: 'vllm/engine/llm_engine.py', target: 'vllm/core/scheduler.py', relation: 'calls', confidence: 0.94, isExtracted: true },
    { id: 've5', source: 'vllm/core/scheduler.py', target: 'vllm/core/block_manager.py', relation: 'calls', confidence: 0.91, isExtracted: true },
    { id: 've6', source: 'tests/kernels/test_fp8.py', target: 'csrc/quantization/fp8_gemm.cu::fp8_gemm_kernel', relation: 'calls', confidence: 0.96, isExtracted: true },
    { id: 've7', source: 'vllm/engine/llm_engine.py', target: 'vllm/model_executor/models/llama.py', relation: 'inferred', confidence: 0.82, isExtracted: false },
    { id: 've8', source: 'vllm/engine/llm_engine.py', target: 'vllm/model_executor/layers/sampler.py', relation: 'calls', confidence: 0.89, isExtracted: true },
  ],
};

// 3. LANGCHAIN PROJECT GRAPH
export const LANGCHAIN_PROJECT_GRAPH: ASTGraphData = {
  metadata: {
    totalFiles: 210,
    totalFunctions: 640,
    totalClasses: 190,
    generatedAt: '2026-08-29T10:30:00Z',
    repoName: 'langchain-ai/langchain (Agentic AI & Chains)',
  },
  godNodes: [
    'libs/core/langchain_core/runnables/base.py',
    'libs/core/langchain_core/language_models/chat_models.py',
    'libs/langchain/langchain/agents/agent.py',
  ],
  communities: {
    1: { id: 1, name: 'LangChain Core & Runnables', color: '#8b5cf6', nodeCount: 16, description: 'LCEL expression language, runnable bindings, and async streaming pipeline' },
    2: { id: 2, name: 'Chat Models & Providers', color: '#3b82f6', nodeCount: 12, description: 'OpenAI, Anthropic, Gemini, and Ollama model wrappers' },
    3: { id: 3, name: 'Autonomous Agent Executors', color: '#10b981', nodeCount: 14, description: 'Tool calling loops, plan-and-solve engines, and memory management' },
  },
  nodes: [
    { id: 'libs/core/langchain_core/runnables/base.py', label: 'RunnableSerializable', type: 'class', file: 'libs/core/langchain_core/runnables/base.py', line: 45, communityId: 1, communityName: 'LangChain Core & Runnables', confidence: 0.98, degree: 14, isGodNode: true, isTarget: true },
    { id: 'libs/core/langchain_core/runnables/config.py', label: 'merge_configs()', type: 'function', file: 'libs/core/langchain_core/runnables/config.py', line: 78, communityId: 1, communityName: 'LangChain Core & Runnables', confidence: 0.95, degree: 7, isTarget: true },
    { id: 'libs/core/langchain_core/language_models/chat_models.py', label: 'BaseChatModel', type: 'class', file: 'libs/core/langchain_core/language_models/chat_models.py', line: 120, communityId: 2, communityName: 'Chat Models & Providers', confidence: 0.96, degree: 11, isGodNode: true },
    { id: 'libs/langchain/langchain/agents/agent.py', label: 'AgentExecutor', type: 'class', file: 'libs/langchain/langchain/agents/agent.py', line: 95, communityId: 3, communityName: 'Autonomous Agent Executors', confidence: 0.94, degree: 12, isGodNode: true },
    { id: 'libs/langchain/langchain/tools/base.py', label: 'BaseTool', type: 'class', file: 'libs/langchain/langchain/tools/base.py', line: 34, communityId: 3, communityName: 'Autonomous Agent Executors', confidence: 0.91, degree: 8 },
  ],
  edges: [
    { id: 'le1', source: 'libs/core/langchain_core/runnables/base.py', target: 'libs/core/langchain_core/runnables/config.py', relation: 'calls', confidence: 0.98, isExtracted: true },
    { id: 'le2', source: 'libs/core/langchain_core/language_models/chat_models.py', target: 'libs/core/langchain_core/runnables/base.py', relation: 'extends', confidence: 0.97, isExtracted: true },
    { id: 'le3', source: 'libs/langchain/langchain/agents/agent.py', target: 'libs/core/langchain_core/language_models/chat_models.py', relation: 'calls', confidence: 0.95, isExtracted: true },
    { id: 'le4', source: 'libs/langchain/langchain/agents/agent.py', target: 'libs/langchain/langchain/tools/base.py', relation: 'calls', confidence: 0.93, isExtracted: true },
  ],
};

// 4. REPOSITORY CATALOG
export const REPOSITORY_GRAPH_CATALOG: Record<string, RepositoryGraphInfo> = {
  gitscout: {
    id: 'gitscout',
    name: 'GitScout / OSS Terminal',
    owner: 'antigravity-ai',
    stars: 1240,
    language: 'Python + TypeScript',
    description: 'Current Project Architecture: 78 AST Nodes across 6 Subsystems (FastAPI, Scrapers, AI Triage, Dispatchers, Billing, Next.js)',
    avatarUrl: 'https://avatars.githubusercontent.com/u/138139589?v=4',
    data: GITSCOUT_PROJECT_GRAPH,
  },
  vllm: {
    id: 'vllm',
    name: 'vllm-project/vllm',
    owner: 'vllm-project',
    stars: 28400,
    language: 'Python + C++/CUDA',
    description: 'High-Throughput and Memory-Efficient LLM Inference and Serving Engine',
    avatarUrl: 'https://avatars.githubusercontent.com/u/138139589?v=4',
    data: VLLM_PROJECT_GRAPH,
  },
  langchain: {
    id: 'langchain',
    name: 'langchain-ai/langchain',
    owner: 'langchain-ai',
    stars: 94500,
    language: 'Python',
    description: 'Building applications with LLMs through composability and autonomous agent runnables',
    avatarUrl: 'https://avatars.githubusercontent.com/u/126733545?v=4',
    data: LANGCHAIN_PROJECT_GRAPH,
  },
};
